/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a launcheradaptor -c LauncherAdaptor -i src/launcher.h -l Launcher /root/Downloads/cutefish/launcher/src/org.cutefish.Launcher.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef LAUNCHERADAPTOR_H
#define LAUNCHERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "src/launcher.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.cutefish.Launcher
 */
class LauncherAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.cutefish.Launcher")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.cutefish.Launcher\">\n"
"    <method name=\"show\"/>\n"
"    <method name=\"hide\"/>\n"
"    <method name=\"toggle\"/>\n"
"  </interface>\n"
        "")
public:
    LauncherAdaptor(Launcher *parent);
    virtual ~LauncherAdaptor();

    inline Launcher *parent() const
    { return static_cast<Launcher *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void hide();
    void show();
    void toggle();
Q_SIGNALS: // SIGNALS
};

#endif
